{
  den.aspects.plasma.provides.menu.homeManager.xdg.configFile."menus/applications-kmenuedit.menu".text = ''
    <!DOCTYPE Menu PUBLIC '-//freedesktop//DTD Menu 1.0//EN' 'http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd'>
    <Menu>
      <Menu>
        <Name>Graphics</Name>
        <Exclude>
        <Filename>okularApplication_md.desktop</Filename>
        <Filename>okularApplication_djvu.desktop</Filename>
        <Filename>okularApplication_pdf.desktop</Filename>
        <Filename>okularApplication_ghostview.desktop</Filename>
        <Filename>okularApplication_dvi.desktop</Filename>
        <Filename>okularApplication_fb.desktop</Filename>
        <Filename>okularApplication_epub.desktop</Filename>
        <Filename>okularApplication_comicbook.desktop</Filename>
        <Filename>okularApplication_txt.desktop</Filename>
        <Filename>okularApplication_tiff.desktop</Filename>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>org.kde.koko.desktop</Filename>
        <Filename>org.kde.gwenview.desktop</Filename>
        <Filename>okularApplication_mobi.desktop</Filename>
        <Filename>org.flameshot.Flameshot.desktop</Filename>
        <Filename>photocrea.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
        <Menu>
        <Name>More</Name>
        <Layout/>
        <Exclude>
          <Filename>org.kde.kcolorchooser.desktop</Filename>
        </Exclude>
        </Menu>
      </Menu>
      <Menu>
        <Name>Internet</Name>
        <Exclude>
        <Filename>org.cockpit_project.CockpitClient.desktop</Filename>
        <Filename>org.kde.bluedevilwizard.desktop</Filename>
        <Filename>bssh.desktop</Filename>
        <Filename>bvnc.desktop</Filename>
        <Filename>org.kde.knetattach.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>discord.desktop</Filename>
        <Filename>jdownloader.desktop</Filename>
        <Filename>org.kde.krdpserver.desktop</Filename>
        <Filename>org.kde.kdeconnect.app.desktop</Filename>
        <Filename>mailspring.desktop</Filename>
        <Filename>org.kde.krdc.desktop</Filename>
        <Filename>motrix.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>rustdesk.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        <Filename>thorium-browser-avx2.desktop</Filename>
        <Filename>org.remmina.Remmina.desktop</Filename>
        <Filename>org.kde.bluedevilsendfile.desktop</Filename>
        <Filename>org.kde.kdeconnect.sms.desktop</Filename>
        <Filename>org.remmina.Remmina-file.desktop</Filename>
        <Filename>zen.desktop</Filename>
        <Filename>org.kde.kdeconnect.nonplasma.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
      </Menu>
      <Menu>
        <Name>Multimedia</Name>
        <Menu>
        <Name>lsp-plugins</Name>
        <Deleted/>
        </Menu>
        <Layout>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
        <Exclude>
        <Filename>org.kde.audiotube.desktop</Filename>
        <Filename>audacity.desktop</Filename>
        <Filename>calf.desktop</Filename>
        <Filename>com.github.wwmm.easyeffects.desktop</Filename>
        <Filename>org.kde.kmix.desktop</Filename>
        <Filename>qv4l2.desktop</Filename>
        <Filename>qvidcap.desktop</Filename>
        <Filename>org.rncbc.qtractor.desktop</Filename>
        <Filename>musikcube.desktop</Filename>
        <Filename>ncspot.desktop</Filename>
        <Filename>org.kde.kid3-qt.desktop</Filename>
        <Filename>org.kde.kamoso.desktop</Filename>
        <Filename>vlc.desktop</Filename>
        </Exclude>
        <Include/>
      </Menu>
      <Menu>
        <Name>Science</Name>
        <Deleted/>
      </Menu>
      <Menu>
        <Name>.hidden</Name>
        <Include>
        <Filename>org.cockpit_project.CockpitClient.desktop</Filename>
        <Filename>okularApplication_md.desktop</Filename>
        <Filename>okularApplication_djvu.desktop</Filename>
        <Filename>okularApplication_pdf.desktop</Filename>
        <Filename>okularApplication_ghostview.desktop</Filename>
        <Filename>electron38.desktop</Filename>
        <Filename>electron37.desktop</Filename>
        <Filename>cmake-gui.desktop</Filename>
        <Filename>org.kde.kommit.merge.desktop</Filename>
        <Filename>org.kde.kommit.diff.desktop</Filename>
        <Filename>assistant.desktop</Filename>
        <Filename>qdbusviewer.desktop</Filename>
        <Filename>linguist.desktop</Filename>
        <Filename>designer.desktop</Filename>
        <Filename>okularApplication_fb.desktop</Filename>
        <Filename>okularApplication_epub.desktop</Filename>
        <Filename>okularApplication_comicbook.desktop</Filename>
        <Filename>okularApplication_txt.desktop</Filename>
        <Filename>okularApplication_tiff.desktop</Filename>
        <Filename>org.kde.bluedevilwizard.desktop</Filename>
        <Filename>bssh.desktop</Filename>
        <Filename>bvnc.desktop</Filename>
        <Filename>org.kde.knetattach.desktop</Filename>
        <Filename>calf.desktop</Filename>
        <Filename>qv4l2.desktop</Filename>
        <Filename>qvidcap.desktop</Filename>
        <Filename>avahi-discover.desktop</Filename>
        <Filename>jconsole-java-openjdk.desktop</Filename>
        <Filename>jshell-java-openjdk.desktop</Filename>
        <Filename>nvim.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>org.kde.kmenuedit.desktop</Filename>
        <Filename>okularApplication_mobi.desktop</Filename>
        <Filename>btop.desktop</Filename>
        <Filename>bauh_tray.desktop</Filename>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog.desktop</Filename>
        <Filename>org.kde.dolphin.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>jetbrains-idea-ce.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        <Filename>rio.desktop</Filename>
        <Filename>systemsettings.desktop</Filename>
        <Filename>nvtop.desktop</Filename>
        <Filename>org.kde.kfontinst.desktop</Filename>
        <Filename>org.kde.kcolorschemeeditor.desktop</Filename>
        <Filename>org.kde.bluedevilsendfile.desktop</Filename>
        <Filename>org.remmina.Remmina-file.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt.desktop</Filename>
        <Filename>zps.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt5.desktop</Filename>
        <Filename>org.kde.klipper.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog6.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>org.kde.kwrite.desktop</Filename>
        <Filename>scrcpy.desktop</Filename>
        <Filename>scrcpy-console.desktop</Filename>
        <Filename>org.kde.kmag.desktop</Filename>
        <Filename>Optimizadores.desktop</Filename>
        <Filename>xplr.desktop</Filename>
        <Filename>org.freedesktop.Xwayland.desktop</Filename>
        <Filename>org.kde.ark.desktop</Filename>
        <Filename>visidata.desktop</Filename>
        <Filename>nnn.desktop</Filename>
        <Filename>clifm.desktop</Filename>
        <Filename>com.github.tchx84.Flatseal.desktop</Filename>
        <Filename>org.kde.kmix.desktop</Filename>
        <Filename>org.kde.krdpserver.desktop</Filename>
        <Filename>org.rncbc.qtractor.desktop</Filename>
        <Filename>org.kde.kdeconnect.nonplasma.desktop</Filename>
        <Filename>org.kde.kdeconnect.sms.desktop</Filename>
        <Filename>org.kde.konsole.desktop</Filename>
        <Filename>org.kde.drkonqi.coredump.gui.desktop</Filename>
        <Filename>gsharp.desktop</Filename>
        <Filename>dbeaver-ce.desktop</Filename>
        <Filename>kde_wacom_tabletfinder.desktop</Filename>
        <Filename>jetbrains-idea.desktop</Filename>
        <Filename>ms-office-protocol-handler.desktop</Filename>
        <Filename>Waydroid.desktop</Filename>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>vim.desktop</Filename>
        <Filename>qtscrcpy.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>emacsclient.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>gvim.desktop</Filename>
        <Filename>ipython.desktop</Filename>
        <Filename>sakura.desktop</Filename>
        <Filename>kcm_nighttime.desktop</Filename>
        <Filename>ClamAV-GUI.desktop</Filename>
        <Filename>cmd.desktop</Filename>
        <Filename>org.kde.plasma-interactiveconsole.desktop</Filename>
        <Filename>insomnia.desktop</Filename>
        <Filename>waydroid.io.github.muntashirakon.AppManager.desktop</Filename>
        <Filename>waydroid.com.aurora.store.desktop</Filename>
        <Filename>waydroid.com.azure.authenticator.desktop</Filename>
        <Filename>waydroid.com.google.android.apps.authenticator2.desktop</Filename>
        <Filename>waydroid.com.badoo.mobile.desktop</Filename>
        <Filename>waydroid.ls.bloomee.musicplayer.desktop</Filename>
        <Filename>waydroid.enterprises.dating.boo.desktop</Filename>
        <Filename>waydroid.com.bumble.app.desktop</Filename>
        <Filename>waydroid.com.looker.droidify.desktop</Filename>
        <Filename>waydroid.com.facebook.katana.desktop</Filename>
        <Filename>waydroid.org.fdroid.fdroid.desktop</Filename>
        <Filename>waydroid.de.marmaro.krt.ffupdater.desktop</Filename>
        <Filename>waydroid.com.android.documentsui.desktop</Filename>
        <Filename>waydroid.org.forkgram.messenger.desktop</Filename>
        <Filename>waydroid.com.android.vending.desktop</Filename>
        <Filename>waydroid.io.github.forkmaintainers.iceraven.desktop</Filename>
        <Filename>waydroid.com.instagram.android.desktop</Filename>
        <Filename>waydroid.com.oasisfeng.island.fdroid.desktop</Filename>
        <Filename>waydroid.com.f0x1d.logfox.desktop</Filename>
        <Filename>waydroid.com.google.android.apps.maps.desktop</Filename>
        <Filename>waydroid.com.mixplorer.desktop</Filename>
        <Filename>waydroid.com.dergoogler.mmrl.desktop</Filename>
        <Filename>waydroid.com.machiav3lli.backup.desktop</Filename>
        <Filename>waydroid.com.microsoft.office.outlook.desktop</Filename>
        <Filename>waydroid.com.michaeltroger.gruenerpass.desktop</Filename>
        <Filename>waydroid.com.mirfatif.permissionmanagerx.desktop</Filename>
        <Filename>waydroid.com.carriez.flutter_hbb.desktop</Filename>
        <Filename>waydroid.com.saludsa.central.desktop</Filename>
        <Filename>waydroid.eu.darken.sdmse.desktop</Filename>
        <Filename>waydroid.hhagetgjv.hb.hmnq.desktop</Filename>
        <Filename>waydroid.com.android.settings.desktop</Filename>
        <Filename>waydroid.cu.axel.smartdock.desktop</Filename>
        <Filename>waydroid.com.voicemaker.android.desktop</Filename>
        <Filename>waydroid.com.microsoft.teams.desktop</Filename>
        <Filename>waydroid.com.tinder.desktop</Filename>
        <Filename>waydroid-open.desktop</Filename>
        </Include>
        <Exclude>
        <Filename>org.gnome.baobab.desktop</Filename>
        <Filename>org.kde.kate.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        <Filename>stacer.desktop</Filename>
        <Filename>dev.zed.Zed.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>org.corectrl.CoreCtrl.desktop</Filename>
        <Filename>zen.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>dbeaver-ce.desktop</Filename>
        <Filename>com.github.tchx84.Flatseal.desktop</Filename>
        <Filename>gsharp.desktop</Filename>
        <Filename>okularApplication_comicbook.desktop</Filename>
        <Filename>okularApplication_pdf.desktop</Filename>
        <Filename>okularApplication_djvu.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt5.desktop</Filename>
        <Filename>org.kde.ark.desktop</Filename>
        <Filename>org.kde.kdeconnect.nonplasma.desktop</Filename>
        <Filename>org.kde.kmix.desktop</Filename>
        <Filename>org.kde.krdpserver.desktop</Filename>
        <Filename>org.rncbc.qtractor.desktop</Filename>
        <Filename>org.kde.kdeconnect.sms.desktop</Filename>
        <Filename>visidata.desktop</Filename>
        <Filename>org.kde.drkonqi.coredump.gui.desktop</Filename>
        <Filename>Waydroid.desktop</Filename>
        <Filename>org.freedesktop.Xwayland.desktop</Filename>
        <Filename>nnn.desktop</Filename>
        <Filename>org.kde.kwrite.desktop</Filename>
        <Filename>okularApplication_fb.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>scrcpy-console.desktop</Filename>
        <Filename>scrcpy.desktop</Filename>
        <Filename>xplr.desktop</Filename>
        <Filename>bauh_tray.desktop</Filename>
        <Filename>org.kde.bluedevilwizard.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>cmake-gui.desktop</Filename>
        <Filename>calf.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        <Filename>org.cockpit_project.CockpitClient.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>org.kde.kommit.diff.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog6.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog.desktop</Filename>
        <Filename>org.kde.dolphin.desktop</Filename>
        <Filename>org.kde.kmenuedit.desktop</Filename>
        <Filename>electron38.desktop</Filename>
        <Filename>bssh.desktop</Filename>
        <Filename>bvnc.desktop</Filename>
        <Filename>org.kde.kommit.merge.desktop</Filename>
        <Filename>jetbrains-idea-ce.desktop</Filename>
        <Filename>org.kde.kcolorschemeeditor.desktop</Filename>
        <Filename>org.kde.kfontinst.desktop</Filename>
        <Filename>org.kde.knetattach.desktop</Filename>
        <Filename>org.kde.klipper.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>avahi-discover.desktop</Filename>
        <Filename>nvim.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        <Filename>okularApplication_epub.desktop</Filename>
        <Filename>okularApplication_mobi.desktop</Filename>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>jconsole-java-openjdk.desktop</Filename>
        <Filename>jshell-java-openjdk.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt.desktop</Filename>
        <Filename>systemsettings.desktop</Filename>
        <Filename>assistant.desktop</Filename>
        <Filename>qdbusviewer.desktop</Filename>
        <Filename>linguist.desktop</Filename>
        <Filename>qv4l2.desktop</Filename>
        <Filename>qvidcap.desktop</Filename>
        <Filename>designer.desktop</Filename>
        <Filename>org.remmina.Remmina-file.desktop</Filename>
        <Filename>rio.desktop</Filename>
        <Filename>org.kde.bluedevilsendfile.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>btop.desktop</Filename>
        <Filename>nvtop.desktop</Filename>
        <Filename>zps.desktop</Filename>
        <Filename>jetbrains-idea.desktop</Filename>
        </Layout>
      </Menu>
      <Menu>
        <Name>Development</Name>
        <Exclude>
        <Filename>electron38.desktop</Filename>
        <Filename>electron37.desktop</Filename>
        <Filename>cmake-gui.desktop</Filename>
        <Filename>org.kde.kommit.merge.desktop</Filename>
        <Filename>org.kde.kommit.diff.desktop</Filename>
        <Filename>assistant.desktop</Filename>
        <Filename>qdbusviewer.desktop</Filename>
        <Filename>linguist.desktop</Filename>
        <Filename>designer.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>insomnia.desktop</Filename>
        <Filename>org.kde.kate.desktop</Filename>
        <Filename>org.kde.kcachegrind.desktop</Filename>
        <Filename>org.kde.kommit.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>windterm.desktop</Filename>
        <Filename>dev.zed.Zed.desktop</Filename>
        <Filename>jetbrains-idea-ce.desktop</Filename>
        <Filename>dbeaver-ce.desktop</Filename>
        <Filename>gsharp.desktop</Filename>
        <Filename>jetbrains-idea.desktop</Filename>
        <Filename>electron36.desktop</Filename>
        <Filename>bruno.desktop</Filename>
        </Exclude>
        <Menu>
        <Name>Web Development</Name>
        <Deleted/>
        </Menu>
        <Menu>
        <Name>Translation</Name>
        <Deleted/>
        </Menu>
        <Layout/>
      </Menu>
      <Menu>
        <Name>Education</Name>
        <Deleted/>
      </Menu>
      <Menu>
        <Name>Help</Name>
        <Layout/>
        <Exclude>
        <Filename>assistant.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        </Exclude>
        <Deleted/>
      </Menu>
      <Include>
        <Filename>org.kde.koko.desktop</Filename>
        <Filename>org.kde.gwenview.desktop</Filename>
        <Filename>org.flameshot.Flameshot.desktop</Filename>
        <Filename>photocrea.desktop</Filename>
        <Filename>org.kde.kcolorchooser.desktop</Filename>
        <Filename>jdownloader.desktop</Filename>
        <Filename>mailspring.desktop</Filename>
        <Filename>org.kde.krdc.desktop</Filename>
        <Filename>motrix.desktop</Filename>
        <Filename>rustdesk.desktop</Filename>
        <Filename>org.kde.kamoso.desktop</Filename>
        <Filename>clamtk.desktop</Filename>
        <Filename>org.kde.kfontview.desktop</Filename>
        <Filename>onlyoffice-desktopeditors.desktop</Filename>
        <Filename>thorium-browser-avx2.desktop</Filename>
        <Filename>virt-manager.desktop</Filename>
        <Filename>audacity.desktop</Filename>
        <Filename>io.missioncenter.MissionCenter.desktop</Filename>
        <Filename>kdesystemsettings.desktop</Filename>
        <Filename>org.kde.kcalc.desktop</Filename>
        <Filename>org.kde.kcharselect.desktop</Filename>
        <Filename>org.kde.kid3-qt.desktop</Filename>
        <Filename>okularApplication_dvi.desktop</Filename>
        <Filename>org.kde.plasma.emojier.desktop</Filename>
        <Filename>veracrypt.desktop</Filename>
        <Filename>kopia-ui.desktop</Filename>
        <Filename>io.github.vikdevelop.SaveDesktop.desktop</Filename>
        <Filename>org.kde.kdeconnect.app.desktop</Filename>
        <Filename>cool-retro-term.desktop</Filename>
        <Filename>windterm.desktop</Filename>
        <Filename>gparted.desktop</Filename>
        <Filename>org.kde.partitionmanager.desktop</Filename>
        <Filename>org.kde.kdf.desktop</Filename>
        <Filename>ventoy.desktop</Filename>
        <Filename>org.kde.isoimagewriter.desktop</Filename>
        <Filename>org.kde.kommit.desktop</Filename>
        <Filename>org.kde.filelight.desktop</Filename>
        <Filename>org.kde.kwikdisk.desktop</Filename>
        <Filename>org.kde.spectacle.desktop</Filename>
        <Filename>org.gnome.baobab.desktop</Filename>
        <Filename>dev.zed.Zed.desktop</Filename>
        <Filename>org.kde.plasma-systemmonitor.desktop</Filename>
        <Filename>org.kde.kjournaldbrowser.desktop</Filename>
        <Filename>org.kde.kbackup.desktop</Filename>
        <Filename>org.remmina.Remmina.desktop</Filename>
        <Filename>org.kde.kgpg.desktop</Filename>
        <Filename>org.kde.kfind.desktop</Filename>
        <Filename>org.kde.ksystemlog.desktop</Filename>
        <Filename>kdiskmark.desktop</Filename>
        <Filename>org.kde.okteta.desktop</Filename>
        <Filename>io.github.thetumultuousunicornofdarkness.cpu-x.desktop</Filename>
        <Filename>lstopo.desktop</Filename>
        <Filename>btrfs-assistant.desktop</Filename>
        <Filename>io.github.ilya_zlobintsev.LACT.desktop</Filename>
        <Filename>toolblex.desktop</Filename>
        <Filename>org.coolercontrol.CoolerControl.desktop</Filename>
        <Filename>tlpui.desktop</Filename>
        <Filename>gtk-lshw.desktop</Filename>
        <Filename>de.feschber.LanMouse.desktop</Filename>
        <Filename>com.ranfdev.DistroShelf.desktop</Filename>
        <Filename>org.corectrl.CoreCtrl.desktop</Filename>
        <Filename>org.kde.krusader.desktop</Filename>
        <Filename>wine-extension-psd.desktop</Filename>
        <Filename>io.github.debasish_patra_1987.linuxthemestore.desktop</Filename>
        <Filename>looking-glass-client.desktop</Filename>
        <Filename>org.kde.kate.desktop</Filename>
        <Filename>discord.desktop</Filename>
        <Filename>com.vixalien.sticky.desktop</Filename>
        <Filename>breezy_desktop.desktop</Filename>
        <Filename>bruno.desktop</Filename>
        <Filename>discord-chat-exporter-gui.desktop</Filename>
        <Filename>io.github.flattool.Warehouse.desktop</Filename>
        <Filename>winapps-launcher.desktop</Filename>
        <Filename>garden.jamie.Morphosis.desktop</Filename>
        <Filename>org.kde.kontainer.desktop</Filename>
        <Filename>downline.desktop</Filename>
        <Filename>yad-icon-browser.desktop</Filename>
        <Filename>ProperTree.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>nitrogen.desktop</Filename>
        <Filename>rtt-rlinux.desktop</Filename>
        <Filename>repair-usb-gui-gtk4.desktop</Filename>
        <Filename>customfetch.desktop</Filename>
        <Filename>io.github.nyre221.kiview.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>com.jaoushingan.WaydroidHelper.desktop</Filename>
        <Filename>jetbrains-datagrip.desktop</Filename>
      </Include>
      <Menu>
        <Name>Terminal</Name>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Internet/Terminal</Old>
        <New>Terminal</New>
      </Move>
      <Menu>
        <Name>Games</Name>
        <NotDeleted/>
        <Exclude>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>net.lutris.Lutris.desktop</Filename>
        <Filename>com.mtkennerly.ludusavi.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        <Filename>protontricks.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>org.prismlauncher.PrismLauncher.desktop</Filename>
        <Filename>io.github.benjamimgois.goverlay.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        </Exclude>
      </Menu>
      <Menu>
        <Name>Games-2</Name>
        <Layout>
        <Merge type="menus"/>
        <Menuname>Arcade</Menuname>
        <Menuname>Card</Menuname>
        <Menuname>Logic</Menuname>
        <Menuname>Board</Menuname>
        <Menuname>Kidsgames</Menuname>
        <Menuname>TacticStrategy</Menuname>
        </Layout>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Games</Old>
        <New>Games-2</New>
      </Move>
      <Menu>
        <Name>Office</Name>
        <Layout>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
        <Exclude>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>onlyoffice-desktopeditors.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        </Exclude>
      </Menu>
      <Menu>
        <Name>System</Name>
        <Exclude>
        <Filename>bauh.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>org.gnome.baobab.desktop</Filename>
        <Filename>btop.desktop</Filename>
        <Filename>bauh_tray.desktop</Filename>
        <Filename>kde_wacom_tabletfinder.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>cachyos-pi.desktop</Filename>
        <Filename>btrfs-assistant.desktop</Filename>
        <Filename>cool-retro-term.desktop</Filename>
        <Filename>clifm.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        <Filename>org.corectrl.CoreCtrl.desktop</Filename>
        <Filename>io.github.thetumultuousunicornofdarkness.cpu-x.desktop</Filename>
        <Filename>org.kde.kmenuedit.desktop</Filename>
        <Filename>org.kde.dolphin.desktop</Filename>
        <Filename>org.kde.kjournaldbrowser.desktop</Filename>
        <Filename>gparted.desktop</Filename>
        <Filename>virt-manager.desktop</Filename>
        <Filename>lstopo.desktop</Filename>
        <Filename>org.kde.isoimagewriter.desktop</Filename>
        <Filename>org.kde.kcolorschemeeditor.desktop</Filename>
        <Filename>org.kde.kdf.desktop</Filename>
        <Filename>kdiskmark.desktop</Filename>
        <Filename>org.kde.partitionmanager.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>org.kde.kwikdisk.desktop</Filename>
        <Filename>io.github.ilya_zlobintsev.LACT.desktop</Filename>
        <Filename>looking-glass-client.desktop</Filename>
        <Filename>gtk-lshw.desktop</Filename>
        <Filename>io.missioncenter.MissionCenter.desktop</Filename>
        <Filename>org.kde.ksystemlog.desktop</Filename>
        <Filename>org.kde.plasma-systemmonitor.desktop</Filename>
        <Filename>avahi-discover.desktop</Filename>
        <Filename>octopi.desktop</Filename>
        <Filename>octopi-notifier.desktop</Filename>
        <Filename>nvtop.desktop</Filename>
        <Filename>octopi-repoeditor.desktop</Filename>
        <Filename>octopi-cachecleaner.desktop</Filename>
        <Filename>jconsole-java-openjdk.desktop</Filename>
        <Filename>jshell-java-openjdk.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>systemsettings.desktop</Filename>
        <Filename>rio.desktop</Filename>
        <Filename>stacer.desktop</Filename>
        <Filename>nnn.desktop</Filename>
        <Filename>kdesystemsettings.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>veracrypt.desktop</Filename>
        <Filename>tlpui.desktop</Filename>
        <Filename>xplr.desktop</Filename>
        <Filename>org.freedesktop.Xwayland.desktop</Filename>
        <Filename>org.kde.yakuake.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>zps.desktop</Filename>
        <Filename>org.kde.konsole.desktop</Filename>
        <Filename>org.kde.drkonqi.coredump.gui.desktop</Filename>
        </Exclude>
        <Include/>
        <Layout>
        <Merge type="menus"/>
        <Menuname>Terminal</Menuname>
        <Menuname>ScreenSavers</Menuname>
        <Menuname>More</Menuname>
        </Layout>
      </Menu>
      <Menu>
        <Name>Utilities</Name>
        <Exclude>
        <Filename>appimagepool.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>org.kde.ark.desktop</Filename>
        <Filename>clamtk.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>org.coolercontrol.CoolerControl.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog6.desktop</Filename>
        <Filename>czkawka-gui.desktop</Filename>
        <Filename>com.ranfdev.DistroShelf.desktop</Filename>
        <Filename>org.kde.filelight.desktop</Filename>
        <Filename>com.github.tchx84.Flatseal.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog.desktop</Filename>
        <Filename>org.kde.kate.desktop</Filename>
        <Filename>org.kde.kbackup.desktop</Filename>
        <Filename>org.kde.kcalc.desktop</Filename>
        <Filename>org.kde.kcharselect.desktop</Filename>
        <Filename>org.kde.kfind.desktop</Filename>
        <Filename>org.corectrl.CoreCtrl.desktop</Filename>
        <Filename>org.kde.kfontinst.desktop</Filename>
        <Filename>org.kde.kfontview.desktop</Filename>
        <Filename>org.kde.kgpg.desktop</Filename>
        <Filename>org.kde.klipper.desktop</Filename>
        <Filename>org.gnome.baobab.desktop</Filename>
        <Filename>org.kde.kmag.desktop</Filename>
        <Filename>org.kde.kwrite.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>io.github.debasish_patra_1987.linuxthemestore.desktop</Filename>
        <Filename>nvim.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        <Filename>org.kde.okteta.desktop</Filename>
        <Filename>de.feschber.LanMouse.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt5.desktop</Filename>
        <Filename>protontricks.desktop</Filename>
        <Filename>org.moson.pacseek.desktop</Filename>
        <Filename>protontricks-launch.desktop</Filename>
        <Filename>org.kde.krusader.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>org.kde.plasma.emojier.desktop</Filename>
        <Filename>scrcpy-console.desktop</Filename>
        <Filename>org.kde.spectacle.desktop</Filename>
        <Filename>scrcpy.desktop</Filename>
        <Filename>stacer.desktop</Filename>
        <Filename>io.github.vikdevelop.SaveDesktop.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>ventoy.desktop</Filename>
        <Filename>toolblex.desktop</Filename>
        <Filename>visidata.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        <Filename>kopia-ui.desktop</Filename>
        <Filename>winetricks.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>dev.zed.Zed.desktop</Filename>
        <Filename>Waydroid.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt.desktop</Filename>
        <Filename>com.vixalien.sticky.desktop</Filename>
        <Filename>shutter-encoder.desktop</Filename>
        <Filename>breezy_desktop.desktop</Filename>
        <Filename>bleachbit-admin.desktop</Filename>
        <Filename>discord-chat-exporter-gui.desktop</Filename>
        <Filename>adbfileexplorer.desktop</Filename>
        <Filename>android-file-transfer.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>escrcpy.desktop</Filename>
        <Filename>ms-office-protocol-handler.desktop</Filename>
        <Filename>scrcpy-launcher.desktop</Filename>
        <Filename>qtscrcpy.desktop</Filename>
        <Filename>io.github.flattool.Warehouse.desktop</Filename>
        <Filename>com.jaoushingan.WaydroidHelper.desktop</Filename>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>winapps-launcher.desktop</Filename>
        <Filename>garden.jamie.Morphosis.desktop</Filename>
        <Filename>vim.desktop</Filename>
        <Filename>org.kde.kontainer.desktop</Filename>
        <Filename>downline.desktop</Filename>
        <Filename>emacsclient.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>gvim.desktop</Filename>
        <Filename>ipython.desktop</Filename>
        <Filename>nitrogen.desktop</Filename>
        <Filename>sakura.desktop</Filename>
        <Filename>rtt-rlinux.desktop</Filename>
        <Filename>repair-usb-gui-gtk4.desktop</Filename>
        <Filename>aya.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>aya.desktop</Filename>
        <Filename>emacsclient.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>gvim.desktop</Filename>
        <Filename>ipython.desktop</Filename>
        <Filename>io.github.nyre221.kiview.desktop</Filename>
        <Filename>nitrogen.desktop</Filename>
        <Filename>repair-usb-gui-gtk4.desktop</Filename>
        <Filename>rtt-rlinux.desktop</Filename>
        <Filename>sakura.desktop</Filename>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
      </Menu>
      <Menu>
        <Name>XUtilities</Name>
        <Deleted/>
      </Menu>
      <Move>
        <Old>Utilities/XUtilities</Old>
        <New>XUtilities</New>
      </Move>
      <Exclude>
        <Filename>nvim.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        <Filename>org.kde.kmenuedit.desktop</Filename>
        <Filename>okularApplication_mobi.desktop</Filename>
        <Filename>btop.desktop</Filename>
        <Filename>bauh_tray.desktop</Filename>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog.desktop</Filename>
        <Filename>org.kde.dolphin.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>protontricks.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>zen.desktop</Filename>
        <Filename>org.prismlauncher.PrismLauncher.desktop</Filename>
        <Filename>io.github.benjamimgois.goverlay.desktop</Filename>
        <Filename>jetbrains-idea-ce.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        <Filename>rio.desktop</Filename>
        <Filename>systemsettings.desktop</Filename>
        <Filename>protontricks-launch.desktop</Filename>
        <Filename>winetricks.desktop</Filename>
        <Filename>com.mtkennerly.ludusavi.desktop</Filename>
        <Filename>net.lutris.Lutris.desktop</Filename>
        <Filename>musikcube.desktop</Filename>
        <Filename>vlc.desktop</Filename>
        <Filename>ncspot.desktop</Filename>
        <Filename>bauh.desktop</Filename>
        <Filename>cachyos-pi.desktop</Filename>
        <Filename>octopi-repoeditor.desktop</Filename>
        <Filename>org.moson.pacseek.desktop</Filename>
        <Filename>octopi-cachecleaner.desktop</Filename>
        <Filename>octopi.desktop</Filename>
        <Filename>octopi-notifier.desktop</Filename>
        <Filename>nvtop.desktop</Filename>
        <Filename>org.kde.kfontinst.desktop</Filename>
        <Filename>org.kde.kcolorschemeeditor.desktop</Filename>
        <Filename>org.kde.bluedevilsendfile.desktop</Filename>
        <Filename>org.remmina.Remmina-file.desktop</Filename>
        <Filename>appimagepool.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt.desktop</Filename>
        <Filename>zps.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt5.desktop</Filename>
        <Filename>org.kde.klipper.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog6.desktop</Filename>
        <Filename>org.kde.kwrite.desktop</Filename>
        <Filename>scrcpy.desktop</Filename>
        <Filename>scrcpy-console.desktop</Filename>
        <Filename>org.kde.kmag.desktop</Filename>
        <Filename>Optimizadores.desktop</Filename>
        <Filename>stacer.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        <Filename>czkawka-gui.desktop</Filename>
        <Filename>org.kde.kcachegrind.desktop</Filename>
        <Filename>org.kde.audiotube.desktop</Filename>
        <Filename>xplr.desktop</Filename>
        <Filename>org.freedesktop.Xwayland.desktop</Filename>
        <Filename>org.kde.ark.desktop</Filename>
        <Filename>visidata.desktop</Filename>
        <Filename>nnn.desktop</Filename>
        <Filename>org.kde.yakuake.desktop</Filename>
        <Filename>clifm.desktop</Filename>
        <Filename>com.github.wwmm.easyeffects.desktop</Filename>
        <Filename>com.github.tchx84.Flatseal.desktop</Filename>
        <Filename>org.kde.kmix.desktop</Filename>
        <Filename>org.kde.krdpserver.desktop</Filename>
        <Filename>org.rncbc.qtractor.desktop</Filename>
        <Filename>org.kde.kdeconnect.nonplasma.desktop</Filename>
        <Filename>org.kde.kdeconnect.sms.desktop</Filename>
        <Filename>Waydroid.desktop</Filename>
        <Filename>dbeaver-ce.desktop</Filename>
        <Filename>kde_wacom_tabletfinder.desktop</Filename>
        <Filename>shutter-encoder.desktop</Filename>
        <Filename>DaVinciControlPanelsSetup.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>pacmanager.desktop</Filename>
        <Filename>waydroid-open.desktop</Filename>
        <Filename>insomnia.desktop</Filename>
      </Exclude>
      <Menu>
        <Name>Gaming</Name>
        <Directory>Gaming.directory</Directory>
        <Include>
        <Filename>protontricks.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>org.prismlauncher.PrismLauncher.desktop</Filename>
        <Filename>io.github.benjamimgois.goverlay.desktop</Filename>
        <Filename>protontricks-launch.desktop</Filename>
        <Filename>winetricks.desktop</Filename>
        <Filename>com.mtkennerly.ludusavi.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        <Filename>net.lutris.Lutris.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        </Include>
        <Exclude>
        <Filename>steam.desktop</Filename>
        <Filename>pacmanager.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>protontricks.desktop</Filename>
        <Filename>protontricks-launch.desktop</Filename>
        <Filename>winetricks.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>net.davidotek.pupgui2.desktop</Filename>
        <Filename>steam-native.desktop</Filename>
        <Filename>io.github.benjamimgois.goverlay.desktop</Filename>
        <Filename>net.lutris.Lutris.desktop</Filename>
        <Filename>com.mtkennerly.ludusavi.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        </Layout>
      </Menu>
      <Menu>
        <Name>Players</Name>
        <Directory>Players.directory</Directory>
        <Include>
        <Filename>musikcube.desktop</Filename>
        <Filename>vlc.desktop</Filename>
        <Filename>ncspot.desktop</Filename>
        </Include>
        <Layout>
        <Merge type="files"/>
        <Filename>musikcube.desktop</Filename>
        <Filename>vlc.desktop</Filename>
        <Filename>ncspot.desktop</Filename>
        </Layout>
        <Menu>
        <Name>Software</Name>
        <Directory>Software.directory</Directory>
        </Menu>
      </Menu>
      <Menu>
        <Name>Software</Name>
        <NotDeleted/>
        <Include>
        <Filename>bauh.desktop</Filename>
        <Filename>cachyos-pi.desktop</Filename>
        <Filename>octopi-repoeditor.desktop</Filename>
        <Filename>org.moson.pacseek.desktop</Filename>
        <Filename>octopi-cachecleaner.desktop</Filename>
        <Filename>octopi.desktop</Filename>
        <Filename>octopi-notifier.desktop</Filename>
        <Filename>appimagepool.desktop</Filename>
        <Filename>pacmanager.desktop</Filename>
        </Include>
        <Exclude>
        <Filename>io.github.debasish_patra_1987.linuxthemestore.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>bauh.desktop</Filename>
        <Filename>appimagepool.desktop</Filename>
        <Filename>cachyos-pi.desktop</Filename>
        <Filename>octopi-repoeditor.desktop</Filename>
        <Filename>octopi.desktop</Filename>
        <Filename>octopi-cachecleaner.desktop</Filename>
        <Filename>octopi-notifier.desktop</Filename>
        <Filename>org.moson.pacseek.desktop</Filename>
        <Filename>pacmanager.desktop</Filename>
        </Layout>
      </Menu>
      <Move>
        <Old>Players/Software</Old>
        <New>Software</New>
      </Move>
      <Menu>
        <Name>Terminal-2</Name>
        <Layout/>
        <NotDeleted/>
        <Include/>
        <Exclude>
        <Filename>windterm.desktop</Filename>
        </Exclude>
      </Menu>
      <Move>
        <Old>Terminal</Old>
        <New>Terminal-2</New>
      </Move>
      <Menu>
        <Name>Optimizadores</Name>
        <Layout>
        <Merge type="files"/>
        <Filename>stacer.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        </Layout>
        <Directory>Optimizadores.directory</Directory>
        <Include>
        <Filename>stacer.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        <Filename>czkawka-gui.desktop</Filename>
        <Filename>org.kde.kcachegrind.desktop</Filename>
        </Include>
        <NotDeleted/>
      </Menu>
      <Menu>
        <Name>Players-2</Name>
        <NotDeleted/>
        <Include>
        <Filename>org.kde.audiotube.desktop</Filename>
        </Include>
      </Menu>
      <Move>
        <Old>Players</Old>
        <New>Players-2</New>
      </Move>
      <Menu>
        <Name>Players-3</Name>
        <Layout>
        <Merge type="files"/>
        <Filename>musikcube.desktop</Filename>
        <Filename>vlc.desktop</Filename>
        <Filename>ncspot.desktop</Filename>
        <Filename>org.kde.audiotube.desktop</Filename>
        </Layout>
        <NotDeleted/>
      </Menu>
      <Menu>
        <Name>Optimizadores-2</Name>
        <Layout>
        <Merge type="files"/>
        <Filename>stacer.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        <Filename>czkawka-gui.desktop</Filename>
        <Filename>org.kde.kcachegrind.desktop</Filename>
        </Layout>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Optimizadores</Old>
        <New>Optimizadores-2</New>
      </Move>
      <Move>
        <Old>Players-2</Old>
        <New>Players-3</New>
      </Move>
      <Menu>
        <Name>Optimizadores-3</Name>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Optimizadores-2</Old>
        <New>Optimizadores-3</New>
      </Move>
      <Menu>
        <Name>Terminal-3</Name>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Terminal-2</Old>
        <New>Terminal-3</New>
      </Move>
      <Menu>
        <Name>Optimizadores-4</Name>
        <NotDeleted/>
        <Layout>
        <Merge type="files"/>
        <Filename>stacer.desktop</Filename>
        <Filename>org.kde.sweeper.desktop</Filename>
        <Filename>bleachbit-admin.desktop</Filename>
        <Filename>org.kde.kcachegrind.desktop</Filename>
        </Layout>
        <Include>
        <Filename>bleachbit-admin.desktop</Filename>
        </Include>
        <Exclude/>
      </Menu>
      <Move>
        <Old>Optimizadores-3</Old>
        <New>Optimizadores-4</New>
      </Move>
      <Menu>
        <Name>Systray</Name>
        <Directory>Systray.directory</Directory>
        <Include>
        <Filename>org.kde.yakuake.desktop</Filename>
        <Filename>com.github.wwmm.easyeffects.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>zen.desktop</Filename>
        </Include>
        <NotDeleted/>
        <Exclude>
        <Filename>jetbrains-idea.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>com.github.wwmm.easyeffects.desktop</Filename>
        <Filename>opensnitch_ui.desktop</Filename>
        <Filename>zen.desktop</Filename>
        </Layout>
      </Menu>
      <Menu>
        <Name>Waydroid</Name>
        <Include/>
        <Exclude>
        <Filename>Waydroid.desktop</Filename>
        <Filename>waydroid.io.github.muntashirakon.AppManager.desktop</Filename>
        <Filename>waydroid.com.aurora.store.desktop</Filename>
        <Filename>waydroid.com.azure.authenticator.desktop</Filename>
        <Filename>waydroid.com.google.android.apps.authenticator2.desktop</Filename>
        <Filename>waydroid.com.badoo.mobile.desktop</Filename>
        <Filename>waydroid.ls.bloomee.musicplayer.desktop</Filename>
        <Filename>waydroid.enterprises.dating.boo.desktop</Filename>
        <Filename>waydroid.com.bumble.app.desktop</Filename>
        <Filename>waydroid.com.looker.droidify.desktop</Filename>
        <Filename>waydroid.com.facebook.katana.desktop</Filename>
        <Filename>waydroid.org.fdroid.fdroid.desktop</Filename>
        <Filename>waydroid.de.marmaro.krt.ffupdater.desktop</Filename>
        <Filename>waydroid.com.android.documentsui.desktop</Filename>
        <Filename>waydroid.org.forkgram.messenger.desktop</Filename>
        <Filename>waydroid.com.android.vending.desktop</Filename>
        <Filename>waydroid.io.github.forkmaintainers.iceraven.desktop</Filename>
        <Filename>waydroid.com.instagram.android.desktop</Filename>
        <Filename>waydroid.com.oasisfeng.island.fdroid.desktop</Filename>
        <Filename>waydroid.com.f0x1d.logfox.desktop</Filename>
        <Filename>waydroid.com.google.android.apps.maps.desktop</Filename>
        <Filename>waydroid.com.mixplorer.desktop</Filename>
        <Filename>waydroid.com.dergoogler.mmrl.desktop</Filename>
        <Filename>waydroid.com.machiav3lli.backup.desktop</Filename>
        <Filename>waydroid.com.microsoft.office.outlook.desktop</Filename>
        <Filename>waydroid.com.michaeltroger.gruenerpass.desktop</Filename>
        <Filename>waydroid.com.mirfatif.permissionmanagerx.desktop</Filename>
        <Filename>waydroid.com.carriez.flutter_hbb.desktop</Filename>
        <Filename>waydroid.com.saludsa.central.desktop</Filename>
        <Filename>waydroid.eu.darken.sdmse.desktop</Filename>
        <Filename>waydroid.hhagetgjv.hb.hmnq.desktop</Filename>
        <Filename>waydroid.com.android.settings.desktop</Filename>
        <Filename>waydroid.cu.axel.smartdock.desktop</Filename>
        <Filename>waydroid.com.voicemaker.android.desktop</Filename>
        <Filename>waydroid.com.microsoft.teams.desktop</Filename>
        <Filename>waydroid.com.tinder.desktop</Filename>
        <Filename>waydroid-open.desktop</Filename>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>com.jaoushingan.WaydroidHelper.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>com.jaoushingan.WaydroidHelper.desktop</Filename>
        <Filename>waydroid-open.desktop</Filename>
        </Layout>
        <Deleted/>
      </Menu>
      <Menu>
        <Name>Applications</Name>
        <Exclude>
        <Filename>wine-extension-psd.desktop</Filename>
        <Filename>mobydroid.desktop</Filename>
        <Filename>kcm_nighttime.desktop</Filename>
        <Filename>ClamAV-GUI.desktop</Filename>
        <Filename>cmd.desktop</Filename>
        <Filename>org.kde.plasma-interactiveconsole.desktop</Filename>
        <Filename>customfetch.desktop</Filename>
        <Filename>pacmanager.desktop</Filename>
        <Filename>raccoon.desktop</Filename>
        <Filename>waydroid-open.desktop</Filename>
        </Exclude>
        <Include>
        <Filename>electron36.desktop</Filename>
        </Include>
        <Layout>
        <Merge type="files"/>
        <Filename>wine-protocol-adbps.desktop</Filename>
        <Filename>kcm_mobile_power.desktop</Filename>
        <Filename>explorer.desktop</Filename>
        <Filename>org.kde.kdialog.desktop</Filename>
        <Filename>java-java17-openjdk.desktop</Filename>
        <Filename>kcm_app-permissions.desktop</Filename>
        <Filename>kcm_cron.desktop</Filename>
        <Filename>powershell.desktop</Filename>
        <Filename>kcm_kwintabbox.desktop</Filename>
        <Filename>org.kde.knighttimed.desktop</Filename>
        <Filename>sticker-convert.desktop</Filename>
        <Filename>windows.desktop</Filename>
        <Filename>org.kde.plasma.settings.open.desktop</Filename>
        <Filename>kcm_access.desktop</Filename>
        <Filename>kaccess.desktop</Filename>
        <Filename>kcm_solid_actions.desktop</Filename>
        <Filename>signon-ui.desktop</Filename>
        <Filename>kcm_about-distro.desktop</Filename>
        <Filename>kcm_activities.desktop</Filename>
        <Filename>user-dirs-update-gtk.desktop</Filename>
        <Filename>org.kde.polkit-kde-authentication-agent-1.desktop</Filename>
        <Filename>org.kde.plasma.browser_integration.host.desktop</Filename>
        <Filename>kcm_animations_x11.desktop</Filename>
        <Filename>kcm_animations.desktop</Filename>
        <Filename>org.kde.kwin_x11.killer.desktop</Filename>
        <Filename>org.kde.kwin.killer.desktop</Filename>
        <Filename>kcm_componentchooser.desktop</Filename>
        <Filename>kcm_recentFiles.desktop</Filename>
        <Filename>kcm_filetypes.desktop</Filename>
        <Filename>kcm_keys.desktop</Filename>
        <Filename>kcm_screenlocker.desktop</Filename>
        <Filename>kcm_bluetooth.desktop</Filename>
        <Filename>kcm_baloofile.desktop</Filename>
        <Filename>kcm_plasmasearch.desktop</Filename>
        <Filename>kcm_colors.desktop</Filename>
        <Filename>kcm_feedback.desktop</Filename>
        <Filename>kcm_kwinxwayland.desktop</Filename>
        <Filename>kcm_kwinoptions_x11.desktop</Filename>
        <Filename>kcm_workspace.desktop</Filename>
        <Filename>kwincompositing.desktop</Filename>
        <Filename>kcm_kscreen.desktop</Filename>
        <Filename>kcmspellchecking.desktop</Filename>
        <Filename>kcm_firewall.desktop</Filename>
        <Filename>org.kde.ksshaskpass.desktop</Filename>
        <Filename>kcm_kaccounts.desktop</Filename>
        <Filename>kcm_cursortheme.desktop</Filename>
        <Filename>kcm_breezedecoration.desktop</Filename>
        <Filename>kcm_oxygendecoration.desktop</Filename>
        <Filename>kcm_kwindecoration_x11.desktop</Filename>
        <Filename>kcm_kwindecoration.desktop</Filename>
        <Filename>org.kde.akonadi.configdialog.desktop</Filename>
        <Filename>kcm_kdf.desktop</Filename>
        <Filename>org.kde.drkonqi.desktop</Filename>
        <Filename>org.kde.keditfiletype.desktop</Filename>
        <Filename>kcm_kwin_effects.desktop</Filename>
        <Filename>kcm_kwin_effects_x11.desktop</Filename>
        <Filename>kcm_energyinfo.desktop</Filename>
        <Filename>kcm_krdpserver.desktop</Filename>
        <Filename>kcm_kwin_virtualdesktops_x11.desktop</Filename>
        <Filename>kcm_kwin_virtualdesktops.desktop</Filename>
        <Filename>org.kde.plasmashell.desktop</Filename>
        <Filename>kcm_disks.desktop</Filename>
        <Filename>kcm_style.desktop</Filename>
        <Filename>kcm_desktoptheme.desktop</Filename>
        <Filename>breezestyleconfig.desktop</Filename>
        <Filename>kcm_clock.desktop</Filename>
        <Filename>kcm_wallpaper.desktop</Filename>
        <Filename>kcm_kgamma.desktop</Filename>
        <Filename>kcm_powerdevilprofilesconfig.desktop</Filename>
        <Filename>kcm_fontinst.desktop</Filename>
        <Filename>google-maps-geo-handler.desktop</Filename>
        <Filename>org.kde.plasma-fallback-session-save.desktop</Filename>
        <Filename>kcm_kwin_scripts_x11.desktop</Filename>
        <Filename>kcm_kwin_scripts.desktop</Filename>
        <Filename>wine-extension-chm.desktop</Filename>
        <Filename>kcm_icons.desktop</Filename>
        <Filename>org.kde.gwenview_importer.desktop</Filename>
        <Filename>org.kde.vpnimport.desktop</Filename>
        <Filename>kcm_autostart.desktop</Filename>
        <Filename>jd-containers.desktop</Filename>
        <Filename>org.kde.kdeconnect.handler.desktop</Filename>
        <Filename>org.kde.kdeconnect.daemon.desktop</Filename>
        <Filename>org.kde.kded5.desktop</Filename>
        <Filename>org.kde.kded6.desktop</Filename>
        <Filename>org.kde.kiod6.desktop</Filename>
        <Filename>ktelnetservice5.desktop</Filename>
        <Filename>kcm_nightlight.desktop</Filename>
        <Filename>com.github.maliit.keyboard.desktop</Filename>
        <Filename>kcm_gamecontroller.desktop</Filename>
        <Filename>kcm_qtquicksettings.desktop</Filename>
        <Filename>kcm_notifications.desktop</Filename>
        <Filename>java-java-openjdk.desktop</Filename>
        <Filename>openstreetmap-geo-handler.desktop</Filename>
        <Filename>kcm_webshortcuts.desktop</Filename>
        <Filename>kcm_touchpad.desktop</Filename>
        <Filename>kcm_splashscreen.desktop</Filename>
        <Filename>kcm_sddm.desktop</Filename>
        <Filename>kcm_touchscreen.desktop</Filename>
        <Filename>kcm_trash.desktop</Filename>
        <Filename>org.kde.plasmawindowed.desktop</Filename>
        <Filename>org.freedesktop.impl.portal.desktop.kde.desktop</Filename>
        <Filename>xdg-desktop-portal-gtk.desktop</Filename>
        <Filename>kcm_krunnersettings.desktop</Filename>
        <Filename>kcm_netpref.desktop</Filename>
        <Filename>kcm_landingpage.desktop</Filename>
        <Filename>kcm_proxy.desktop</Filename>
        <Filename>kcm_mobile_hotspot.desktop</Filename>
        <Filename>qemu.desktop</Filename>
        <Filename>kcm_mouse.desktop</Filename>
        <Filename>kcm_cellular_network.desktop</Filename>
        <Filename>kcm_regionandlang.desktop</Filename>
        <Filename>kcm_kwinrules_x11.desktop</Filename>
        <Filename>kcm_kwinrules.desktop</Filename>
        <Filename>kcm_kwintabbox_x11.desktop</Filename>
        <Filename>org.kde.ksecretd.desktop</Filename>
        <Filename>kcm_kded.desktop</Filename>
        <Filename>kcm_smserver.desktop</Filename>
        <Filename>kcm_pulseaudio.desktop</Filename>
        <Filename>kcm_soundtheme.desktop</Filename>
        <Filename>kcm_tablet.desktop</Filename>
        <Filename>kcm_wacomtablet.desktop</Filename>
        <Filename>kcm_keyboard.desktop</Filename>
        <Filename>kcm_virtualkeyboard.desktop</Filename>
        <Filename>kcm_lookandfeel.desktop</Filename>
        <Filename>kcm_bolt.desktop</Filename>
        <Filename>kcm_fonts.desktop</Filename>
        <Filename>kcm_desktoppaths.desktop</Filename>
        <Filename>kcm_users.desktop</Filename>
        <Filename>wheelmap-geo-handler.desktop</Filename>
        <Filename>kcm_mobile_wifi.desktop</Filename>
        <Filename>kcm_networkmanagement.desktop</Filename>
        <Filename>wine.desktop</Filename>
        <Filename>wine-extension-msp.desktop</Filename>
        <Filename>wine-extension-hlp.desktop</Filename>
        <Filename>wine-extension-vbs.desktop</Filename>
        <Filename>userapp-Zen-BVI6D3.desktop</Filename>
        <Filename>org.gnome.Zenity.desktop</Filename>
        <Filename>electron36.desktop</Filename>
        </Layout>
      </Menu>
      <Menu>
        <Name>DaVinciResolve</Name>
        <Layout>
        <Merge type="files"/>
        <Filename>DaVinciControlPanelsSetup.desktop</Filename>
        <Filename>DaVinciResolve.desktop</Filename>
        <Filename>blackmagicraw-speedtest.desktop</Filename>
        <Filename>blackmagicraw-player.desktop</Filename>
        <Filename>shutter-encoder.desktop</Filename>
        </Layout>
        <Include>
        <Filename>shutter-encoder.desktop</Filename>
        <Filename>DaVinciResolve.desktop</Filename>
        <Filename>DaVinciControlPanelsSetup.desktop</Filename>
        <Filename>blackmagicraw-player.desktop</Filename>
        </Include>
        <Exclude/>
        <NotDeleted/>
      </Menu>
      <Menu>
        <Name>Players-4</Name>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Players-3</Old>
        <New>Players-4</New>
      </Move>
      <Menu>
        <Name>Development-2</Name>
        <NotDeleted/>
        <Exclude>
        <Filename>guiscrcpy.desktop</Filename>
        <Filename>uad-ng.desktop</Filename>
        <Filename>qtscrcpy.desktop</Filename>
        <Filename>yad-icon-browser.desktop</Filename>
        <Filename>android-toolkit.desktop</Filename>
        <Filename>stackzy.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>ipython.desktop</Filename>
        <Filename>ProperTree.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>emacsclient.desktop</Filename>
        <Filename>jetbrains-datagrip.desktop</Filename>
        </Exclude>
        <Layout/>
      </Menu>
      <Move>
        <Old>Development</Old>
        <New>Development-2</New>
      </Move>
      <Menu>
        <Name>Android</Name>
        <Directory>Android.directory</Directory>
        <NotDeleted/>
        <Include>
        <Filename>adbfileexplorer.desktop</Filename>
        <Filename>android-file-transfer.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>escrcpy.desktop</Filename>
        <Filename>scrcpy-launcher.desktop</Filename>
        <Filename>qtscrcpy.desktop</Filename>
        <Filename>guiscrcpy.desktop</Filename>
        <Filename>uad-ng.desktop</Filename>
        <Filename>android-toolkit.desktop</Filename>
        <Filename>stackzy.desktop</Filename>
        <Filename>mobydroid.desktop</Filename>
        <Filename>aya.desktop</Filename>
        <Filename>raccoon.desktop</Filename>
        </Include>
        <Exclude>
        <Filename>waydroid-open.desktop</Filename>
        <Filename>jetbrains-datagrip.desktop</Filename>
        </Exclude>
        <Layout>
        <Merge type="files"/>
        <Filename>adbfileexplorer.desktop</Filename>
        <Filename>android-file-transfer.desktop</Filename>
        <Filename>android-toolkit.desktop</Filename>
        <Filename>androidscreencast.desktop</Filename>
        <Filename>escrcpy.desktop</Filename>
        <Filename>aya.desktop</Filename>
        <Filename>qtscrcpy.desktop</Filename>
        <Filename>guiscrcpy.desktop</Filename>
        <Filename>mobydroid.desktop</Filename>
        <Filename>raccoon.desktop</Filename>
        <Filename>scrcpy-launcher.desktop</Filename>
        <Filename>stackzy.desktop</Filename>
        <Filename>uad-ng.desktop</Filename>
        </Layout>
      </Menu>
      <Menu>
        <Name>Utilities-2</Name>
        <Layout>
        <Merge type="menus"/>
        <Menuname>More</Menuname>
        </Layout>
        <NotDeleted/>
        <Exclude>
        <Filename>io.github.nyre221.kiview.desktop</Filename>
        </Exclude>
      </Menu>
      <Menu>
        <Name>.hidden-2</Name>
        <NotDeleted/>
        <Layout>
        <Merge type="files"/>
        <Filename>dbeaver-ce.desktop</Filename>
        <Filename>com.github.tchx84.Flatseal.desktop</Filename>
        <Filename>gsharp.desktop</Filename>
        <Filename>okularApplication_comicbook.desktop</Filename>
        <Filename>okularApplication_pdf.desktop</Filename>
        <Filename>okularApplication_djvu.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt5.desktop</Filename>
        <Filename>org.kde.ark.desktop</Filename>
        <Filename>org.kde.kdeconnect.nonplasma.desktop</Filename>
        <Filename>org.kde.kmix.desktop</Filename>
        <Filename>org.kde.krdpserver.desktop</Filename>
        <Filename>org.rncbc.qtractor.desktop</Filename>
        <Filename>org.kde.kdeconnect.sms.desktop</Filename>
        <Filename>visidata.desktop</Filename>
        <Filename>org.kde.drkonqi.coredump.gui.desktop</Filename>
        <Filename>Waydroid.desktop</Filename>
        <Filename>org.freedesktop.Xwayland.desktop</Filename>
        <Filename>nnn.desktop</Filename>
        <Filename>org.kde.kwrite.desktop</Filename>
        <Filename>okularApplication_fb.desktop</Filename>
        <Filename>steam.desktop</Filename>
        <Filename>scrcpy-console.desktop</Filename>
        <Filename>scrcpy.desktop</Filename>
        <Filename>xplr.desktop</Filename>
        <Filename>bauh_tray.desktop</Filename>
        <Filename>org.kde.bluedevilwizard.desktop</Filename>
        <Filename>org.bleachbit.BleachBit.desktop</Filename>
        <Filename>com.usebottles.bottles.desktop</Filename>
        <Filename>cmake-gui.desktop</Filename>
        <Filename>calf.desktop</Filename>
        <Filename>org.kde.kinfocenter.desktop</Filename>
        <Filename>org.cockpit_project.CockpitClient.desktop</Filename>
        <Filename>code.desktop</Filename>
        <Filename>org.kde.kommit.diff.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog6.desktop</Filename>
        <Filename>org.kde.knewstuff-dialog.desktop</Filename>
        <Filename>org.kde.dolphin.desktop</Filename>
        <Filename>org.kde.kmenuedit.desktop</Filename>
        <Filename>electron38.desktop</Filename>
        <Filename>bssh.desktop</Filename>
        <Filename>bvnc.desktop</Filename>
        <Filename>org.kde.kommit.merge.desktop</Filename>
        <Filename>jetbrains-idea-ce.desktop</Filename>
        <Filename>org.kde.kcolorschemeeditor.desktop</Filename>
        <Filename>org.kde.kfontinst.desktop</Filename>
        <Filename>org.kde.knetattach.desktop</Filename>
        <Filename>org.kde.klipper.desktop</Filename>
        <Filename>kvantummanager.desktop</Filename>
        <Filename>avahi-discover.desktop</Filename>
        <Filename>nvim.desktop</Filename>
        <Filename>okularApplication_epub.desktop</Filename>
        <Filename>okularApplication_mobi.desktop</Filename>
        <Filename>org.kde.okular.desktop</Filename>
        <Filename>jconsole-java-openjdk.desktop</Filename>
        <Filename>jshell-java-openjdk.desktop</Filename>
        <Filename>org.gnupg.pinentry-qt.desktop</Filename>
        <Filename>systemsettings.desktop</Filename>
        <Filename>assistant.desktop</Filename>
        <Filename>qdbusviewer.desktop</Filename>
        <Filename>linguist.desktop</Filename>
        <Filename>qv4l2.desktop</Filename>
        <Filename>qvidcap.desktop</Filename>
        <Filename>designer.desktop</Filename>
        <Filename>org.remmina.Remmina-file.desktop</Filename>
        <Filename>rio.desktop</Filename>
        <Filename>org.kde.bluedevilsendfile.desktop</Filename>
        <Filename>vifm.desktop</Filename>
        <Filename>code-url-handler.desktop</Filename>
        <Filename>yazi.desktop</Filename>
        <Filename>btop.desktop</Filename>
        <Filename>nvtop.desktop</Filename>
        <Filename>zps.desktop</Filename>
        <Filename>jetbrains-idea.desktop</Filename>
        </Layout>
        <Exclude>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>codes.merrit.Nyrna.desktop</Filename>
        </Exclude>
      </Menu>
      <Move>
        <Old>.hidden</Old>
        <New>.hidden-2</New>
      </Move>
      <Move>
        <Old>Utilities</Old>
        <New>Utilities-2</New>
      </Move>
      <Menu>
        <Name>Players-5</Name>
        <NotDeleted/>
      </Menu>
      <Move>
        <Old>Players-4</Old>
        <New>Players-5</New>
      </Move>
      <Layout>
        <Merge type="files"/>
        <Filename>wine-extension-psd.desktop</Filename>
        <Filename>photocrea.desktop</Filename>
        <Filename>onlyoffice-desktopeditors.desktop</Filename>
        <Filename>thorium-browser-avx2.desktop</Filename>
        <Filename>bruno.desktop</Filename>
        <Filename>io.github.debasish_patra_1987.linuxthemestore.desktop</Filename>
        <Filename>jetbrains-datagrip.desktop</Filename>
        <Filename>org.kde.krdc.desktop</Filename>
        <Filename>virt-manager.desktop</Filename>
        <Filename>looking-glass-client.desktop</Filename>
        <Filename>rustdesk.desktop</Filename>
        <Filename>winapps-launcher.desktop</Filename>
        <Filename>audacity.desktop</Filename>
        <Filename>jdownloader.desktop</Filename>
        <Filename>io.missioncenter.MissionCenter.desktop</Filename>
        <Filename>downline.desktop</Filename>
        <Filename>com.vixalien.sticky.desktop</Filename>
        <Filename>org.kde.kate.desktop</Filename>
        <Filename>emacs.desktop</Filename>
        <Filename>discord.desktop</Filename>
        <Filename>discord-chat-exporter-gui.desktop</Filename>
        <Filename>com.ranfdev.DistroShelf.desktop</Filename>
        <Filename>com.github.marhkb.Pods.desktop</Filename>
        <Filename>io.github.flattool.Warehouse.desktop</Filename>
        <Filename>kdesystemsettings.desktop</Filename>
        <Filename>waydroid-show.desktop</Filename>
        <Filename>com.jaoushingan.WaydroidHelper.desktop</Filename>
        <Merge type="menus"/>
        <Menuname>Android</Menuname>
        <Menuname>DaVinciResolve-2</Menuname>
        <Menuname>Software</Menuname>
        <Menuname>Gaming</Menuname>
        <Menuname>Optimizadores-4</Menuname>
        <Filename>org.kde.kamoso.desktop</Filename>
        <Filename>org.kde.kcharselect.desktop</Filename>
        <Filename>org.remmina.Remmina.desktop</Filename>
        <Filename>org.kde.kfontview.desktop</Filename>
        <Filename>org.kde.plasma.emojier.desktop</Filename>
        <Filename>org.kde.gwenview.desktop</Filename>
        <Filename>org.kde.koko.desktop</Filename>
        <Filename>org.kde.kcalc.desktop</Filename>
        <Filename>okularApplication_dvi.desktop</Filename>
        <Filename>garden.jamie.Morphosis.desktop</Filename>
        <Filename>clamtk.desktop</Filename>
        <Filename>org.kde.kid3-qt.desktop</Filename>
        <Filename>org.flameshot.Flameshot.desktop</Filename>
        <Filename>yad-icon-browser.desktop</Filename>
        <Filename>org.kde.krusader.desktop</Filename>
        <Filename>org.kde.spectacle.desktop</Filename>
        <Filename>org.kde.kcolorchooser.desktop</Filename>
        <Filename>breezy_desktop.desktop</Filename>
        <Filename>veracrypt.desktop</Filename>
        <Filename>motrix.desktop</Filename>
        <Filename>org.kde.kommit.desktop</Filename>
        <Filename>kopia-ui.desktop</Filename>
        <Filename>io.github.vikdevelop.SaveDesktop.desktop</Filename>
        <Filename>org.kde.kbackup.desktop</Filename>
        <Filename>org.kde.kgpg.desktop</Filename>
        <Filename>org.kde.kfind.desktop</Filename>
        <Filename>org.kde.kdeconnect.app.desktop</Filename>
        <Filename>cool-retro-term.desktop</Filename>
        <Filename>windterm.desktop</Filename>
        <Filename>gparted.desktop</Filename>
        <Filename>org.kde.partitionmanager.desktop</Filename>
        <Filename>org.kde.kdf.desktop</Filename>
        <Filename>org.kde.filelight.desktop</Filename>
        <Filename>org.gnome.baobab.desktop</Filename>
        <Filename>org.kde.kwikdisk.desktop</Filename>
        <Filename>ventoy.desktop</Filename>
        <Filename>org.kde.isoimagewriter.desktop</Filename>
        <Filename>org.kde.plasma-systemmonitor.desktop</Filename>
        <Filename>repair-usb-gui-gtk4.desktop</Filename>
        <Filename>org.kde.kjournaldbrowser.desktop</Filename>
        <Filename>org.kde.ksystemlog.desktop</Filename>
        <Filename>org.kde.okteta.desktop</Filename>
        <Filename>kdiskmark.desktop</Filename>
        <Filename>io.github.thetumultuousunicornofdarkness.cpu-x.desktop</Filename>
        <Filename>lstopo.desktop</Filename>
        <Filename>btrfs-assistant.desktop</Filename>
        <Filename>gtk-lshw.desktop</Filename>
        <Filename>io.github.ilya_zlobintsev.LACT.desktop</Filename>
        <Filename>org.corectrl.CoreCtrl.desktop</Filename>
        <Filename>tlpui.desktop</Filename>
        <Filename>org.coolercontrol.CoolerControl.desktop</Filename>
        <Filename>ProperTree.desktop</Filename>
        <Filename>de.feschber.LanMouse.desktop</Filename>
        <Filename>toolblex.desktop</Filename>
        <Filename>io.github.nyre221.kiview.desktop</Filename>
        <Filename>customfetch.desktop</Filename>
        <Menuname>Players-5</Menuname>
        <Menuname>Systray</Menuname>
        <Menuname>Utilities-2</Menuname>
        <Menuname>Development-2</Menuname>
        <Menuname>System</Menuname>
        <Menuname>Applications</Menuname>
        <Menuname>.hidden-2</Menuname>
        <Menuname>Office</Menuname>
        <Menuname>Multimedia</Menuname>
        <Menuname>Games-2</Menuname>
        <Menuname>Internet</Menuname>
        <Menuname>Graphics</Menuname>
        <Menuname>Terminal-3</Menuname>
      </Layout>
    </Menu>
  '';
}
