''
    cat >> $buildRoot/.config <<EOF
  CONFIG_USB_F_FS=m
  CONFIG_SYSFS=m
  CONFIG_RAMFS=m
  CONFIG_TMPFS=m
  CONFIG_DEVPTS_FS=m
  CONFIG_PROC_FS=m
  CONFIG_DEVTMPFS=m
  CONFIG_CRYPTO_CRC32C=m
  CONFIG_USB_CONFIGFS=m
  CONFIG_USB_CONFIGFS_F_FS=m
  EOF
''
