''
    cat >> $buildRoot/.config <<EOF
  CONFIG_USB_F_FS=y
  CONFIG_SYSFS=y
  CONFIG_RAMFS=y
  CONFIG_TMPFS=y
  CONFIG_DEVPTS_FS=y
  CONFIG_PROC_FS=y
  CONFIG_DEVTMPFS=y
  CONFIG_USB_CONFIGFS=y
  CONFIG_USB_CONFIGFS_F_FS=y
  EOF
''
