[
  "--set-str DEFAULT_HOSTNAME v7w7r"
  "--set-str DEFAULT_NET_SCH fq"
  "--set-str DEFAULT_TCP_CONG bbr"

  "--set-val HZ 300"
  "--set-val NR_CPUS 8"

  "-e AUTOFS_FS"
  "-e ARM_ALLWINNER_SUN50I_CPUFREQ_NVMEM"
  "-e ANDROID_BINDER_IPC"
  "-e ANDROID_BINDERFS"
  "-e CRYPTO_ZSTD"
  "-e CRYPTO_USER_API_HASH"
  "-e DRM_LIMA"
  "-e DRM_SUN4I"
  "-e F2FS_FS"
  "-e F2FS_CHECK_FS"
  "-e F2FS_FS_COMPRESSION"
  "-e F2FS_FS_LZ4"
  "-e F2FS_FS_LZ4HC"
  "-e F2FS_FS_SECURITY"
  "-e F2FS_FS_ZSTD"
  "-e DEFAULT_BBR"
  "-e USB_ETH"
  "-e USB_LIBCOMPOSITE"
  "-e USB_UAS"
  "-e USB_STORAGE"
  "-e USB_EHCI_HCD"
  "-e USB_OHCI_HCD"
  "-e NVMEM_SUNXI_SID"
  "-e STMMAC_ETH"
  "-e NO_HZ"
  "-e NO_HZ_COMMON"
  "-e NO_HZ_IDLE"
  "-e MMC_SUNXI"
  "-e MDIO_SUN4I"
  "-e PREEMPT_NONE"
  "-e PREEMPT_NONE_BUILD"
  "-e ZRAM_DEF_COMP_LZ4"
  "-e ZRAM_LZ4_COMPRESS"
  "-e TMPFS"
  "-e TMPFS_POSIX_ACL"
  "-e SPARD_WLAN_SUPPORT"
  "-e IR_SUNXI"
  "-e TCP_CONG_BBR"
  "-e TMPFS_POSIX_XATTR"
  "-e USER_NS"
  "-e UNIX"
  "-e XFS_FS"
  "-e XFS_SUPPORT_V4"
  "-e XFS_SUPPORT_ASCII_CI"
  "-e XFS_QUOTA"
  "-e XFS_POSIX_ACL"
  "-e XFS_RT"
  "-e XFS_DRAIN_INTENTS"
  "-e XFS_LIVE_HOOKS"
  "-e XFS_MEMORY_BUFS"
  "-e XFS_BTREE_IN_MEM"
  "-e XFS_ONLINE_SCRUB"
  "-e XFS_ONLINE_REPAIR"
  "-e SUNXI_WATCHDOG"
  "-e VIDEO_SUNXI"
  "-e VIDEO_SUNXI_CEDRUS"

  "-m MFD_AC200"
  "-m MFD_AC200_SUNXI"
  "-m AC200_PHY"
  "-m AC200_PHY_SUNXI"
  "-m MMC_SDHCI"
  "-m NET_SCH_FQ_CODEL"
  "-m USB_MUSB_SUNXI"
  "-m USB_MUSB_HDRC"
  "-m VIRTIO"
  "-m SERIO_SUN4I_PS2"
  "-m SUNXI_ADDR_MGT"
  "-m VIDEO_SUN6I_ISP"
  "-m ZRAM"

  "-d ACPI"
  "-d DEBUG_FS"
  "-d KEXEC"
  "-d KEXEC_JUMP"
  "-d NFC"
  "-d INPUT_JOYSTICK"
  "-d INPUT_TABLET"
  "-d INPUT_TOUCHSCREEN"
  "-d KALLSYMS_ALL"
  "-d HZ_1000"
  "-d MOUSE_PS2"
  "-d NO_HZ_FULL"
  "-d NTSYNC"
  "-d PREEMPT"
  "-d PREEMPT_DYNAMIC"
  "-d PREEMPT_LAZY"
  "-d PREEMPTION"
  "-d PREEMPT_VOLUNTARY"
  "-d PROFILING"
  "-d SECURITY_SELINUX"
  "-d SECURITY_TOMOYO"
  "-d XEN"

  "-d SOUND"
  "-d SND"
  "-d SND_SOC"
  "-d SND_SUN4I_CODEC"
  "-d WLAN_VENDOR_ATH"
  "-d WLAN_VENDOR_BROADCOM"
  "-d WLAN_VENDOR_INTEL"
  "-d WLAN_VENDOR_MARVELL"
  "-d WLAN_VENDOR_TI"
  "-d ZRAM_BACKEND_842"
]
#++ (import ../config/develop.nix)
++ (import ../config/cmdline.nix) { host = ""; }
#++ (import ../config/vendors.nix) { isPC = false; }
