[
  "--set-str DEFAULT_HOSTNAME v7w7r"
  "--set-str DEFAULT_NET_SCH fq"
  "--set-str DEFAULT_TCP_CONG bbr"

  "--set-val HZ 300"
  "--set-val NR_CPUS 8"

  "-e AUTOFS_FS"
  "-e ANDROID_BINDER_IPC"
  "-e ANDROID_BINDERFS"
  "-e CRYPTO_ZSTD"
  "-e CRYPTO_USER_API_HASH"
  "-e DRM_LIMA"
  "-e DRM_SUN4I"
  "-e EXPERIMENTAL"
  "-e F2FS_FS"
  "-e F2FS_CHECK_FS"
  "-e F2FS_FS_COMPRESSION"
  "-e F2FS_FS_LZ4"
  "-e F2FS_FS_LZ4HC"
  "-e F2FS_FS_SECURITY"
  "-e F2FS_FS_ZSTD"
  "-e DEFAULT_BBR"
  "-e DEFAULT_FQ"

  "-e USB_ETH"
  "-e USB_LIBCOMPOSITE"
  "-e USB_F_ETHER"
  "-e USB_UAS"
  "-e USB_STORAGE"
  "-e USB_HID"
  "-e USB_EHCI_HCD"
  "-e USB_OHCI_HCD"
  "-e MMC_BLOCK"
  "-e MMC_SDHCI"
  "-e NVMEM_SUNXI_SID"

  "-e STMMAC_ETH"
  "-e DWMAC_SUN8I"
  "-e PHYLIB"
  "-e SUN8I_EPHY"

  "-e SUN6I_RTC_CCU"
  "-e DUMP_REG"

  "-e MFD_AC200"

  "-e NO_HZ"
  "-e NO_HZ_COMMON"
  "-e NO_HZ_IDLE"
  "-e ICPLUS_PHY"
  "-e FIXED_PHY"
  "-e MMC_SUNXI"
  "-e MDIO_SUN4I"
  "-e PREEMPT_NONE"
  "-e PREEMPT_NONE_BUILD"
  "-e PINCTRL_SUNXI"
  "-e PINCTRL_SUN50I_H616"
  "-e ZRAM_DEF_COMP_LZ4"
  "-e ZRAM_LZ4_COMPRESS"
  "-e TMPFS"
  "-e TMPFS_POSIX_ACL"
  "-e SUNXI_ADDR_MGT"
  "-e PHYLIB"
  "-e SPARD_WLAN_SUPPORT"
  "-e SUNXI_MMC"
  "-e AW_WIFI_DEVICE_UWE5622"
  "-e TCP_CONG_BBR"
  "-e SUN8I_EMAC"
  "-e TMPFS_POSIX_XATTR"
  "-e USER_NS"
  "-e UNIX"
  "-e XFS_FS"
  "-e XFS_SUPPORT_V4"
  "-e XFS_SUPPORT_ASCII_CI"
  "-e XFS_QUOTA"
  "-e XFS_POSIX_ACL"
  "-e XFS_RT"
  "-e XFS_DRAIN_INTENTS"
  "-e XFS_LIVE_HOOKS"
  "-e XFS_MEMORY_BUFS"
  "-e XFS_BTREE_IN_MEM"
  "-e XFS_ONLINE_SCRUB"
  "-e XFS_ONLINE_REPAIR"

  "-m WLAN_UWE5622"
  "-m PHY_SUN6I_DSI"
  "-m SPRDWL_NG"
  "-m TTY_OVERY_SDIO"

  "-m ARM_ALLWINNER_SUN50I_CPUFREQ_NVMEM"
  "-m ARM_SCMI_CPUFREQ"
  "-m NET_SCH_FQ_CODEL"
  "-m SPRDWL_NG"
  "-m TTY_OVERY_SDIO"
  "-m VIRTIO"
  "-m ZRAM"

  "-d ACPI"
  "-d ACCESSIBILITY"
  "-d AW_WIFI_DEVICE_UWE5622"
  "-d DEBUG_FS"
  "-d DRM_RADEON"
  "-d KEXEC"
  "-d KEXEC_JUMP"
  "-d NFC"
  "-d INPUT_JOYSTICK"
  "-d INPUT_TABLET"
  "-d INPUT_TOUCHSCREEN"
  "-d KALLSYMS_ALL"
  "-d HZ_1000"
  "-d INTERCONNECT"
  "-d MOUSE_PS2"
  "-d NO_HZ_FULL"
  "-d NTSYNC"
  "-d PCI"
  "-d PREEMPT"
  "-d PREEMPT_DYNAMIC"
  "-d PREEMPT_LAZY"
  "-d PREEMPTION"
  "-d PREEMPT_VOLUNTARY"
  "-d PROFILING"
  "-d SECURITY_SELINUX"
  "-d SECURITY_TOMOYO"
  "-d XEN"

  "-d SOUND"
  "-d SND"
  "-d SND_SOC"
  "-d SND_SUN4I_CODEC"
  "-d STAGING"
  "-d SPARD_WLAN_SUPPORT"
  "-d WLAN_VENDOR_ATH"
  "-d WLAN_VENDOR_BROADCOM"
  "-d WLAN_VENDOR_INTEL"
  "-d WLAN_VENDOR_MARVELL"
  "-d WLAN_VENDOR_TI"
  "-d WLAN_UWE5622"
  "-d WATCHDOG"
  "-d ZRAM_BACKEND_842"
]
++ (import ../config/develop.nix)
++ (import ../config/cmdline.nix) { host = ""; }
++ (import ../config/vendors.nix) { isPC = false; }
