[
  "--set-str DEFAULT_HOSTNAME v7w7r"
  "--set-str DEFAULT_NET_SCH fq"
  "--set-str DEFAULT_TCP_CONG bbr"

  "--set-val HZ 300"
  "--set-val NR_CPUS 8"

  "-e STMMAC_ETH"
  "-e ARM_ALLWINNER_SUN50I_CPUFREQ_NVMEM"
  "-e ANDROID_BINDER_IPC"
  "-e ANDROID_BINDERFS"
  "-e DMI"
  "-e DMIID"
  "-e F2FS_FS"
  "-e F2FS_CHECK_FS"
  "-e F2FS_FS_COMPRESSION"
  "-e F2FS_FS_LZ4"
  "-e F2FS_FS_LZ4HC"
  "-e F2FS_FS_SECURITY"
  "-e F2FS_FS_ZSTD"
  "-e DEFAULT_BBR"
  "-e USB_LIBCOMPOSITE"
  "-e NO_HZ"
  "-e NO_HZ_COMMON"
  "-e NO_HZ_IDLE"
  "-e PREEMPT_NONE"
  "-e PREEMPT_NONE_BUILD"
  "-e ZRAM_DEF_COMP_LZ4"
  "-e ZRAM_LZ4_COMPRESS"
  "-e TCP_CONG_BBR"
  "-e XFS_FS"
  "-e XFS_SUPPORT_V4"
  "-e XFS_SUPPORT_ASCII_CI"
  "-e XFS_QUOTA"
  "-e XFS_POSIX_ACL"
  "-e XFS_RT"
  "-e XFS_DRAIN_INTENTS"
  "-e XFS_LIVE_HOOKS"
  "-e XFS_MEMORY_BUFS"
  "-e XFS_BTREE_IN_MEM"
  "-e XFS_ONLINE_SCRUB"
  "-e XFS_ONLINE_REPAIR"
  "-e UNISOC_WIFI_PS"
  "-e VIDEO_SUNXI"
  "-e VIDEO_SUNXI_CEDRUS"

  "-m MFD_AC200"
  "-m MFD_AC200_SUNXI"
  "-m AC200_PHY"
  "-m DRM_LIMA"
  "-m AC200_PHY_SUNXI"
  "-m MMC_SDHCI"
  "-m NET_SCH_FQ_CODEL"
  "-m USB_ETH"
  "-m USB_MUSB_SUNXI"
  "-m USB_MUSB_HDRC"
  "-m VIRTIO"
  "-m SERIO_SUN4I_PS2"
  "-m SUNXI_ADDR_MGT"
  "-m WLAN_UWE5621"
  "-m WLAN_UWE5622"
  "-m TTY_OVERY_SDIO"
  "-m VIRT_WIFI"
  "-m USB_UAS"
  "-m VIDEO_SUN6I_ISP"
  "-m ZRAM"

  "-d KEXEC"
  "-d KEXEC_JUMP"
  "-d KALLSYMS_ALL"
  "-d NFC"
  "-d INPUT_JOYSTICK"
  "-d INPUT_TOUCHSCREEN"
  "-d MOUSE_PS2"
  "-d HZ_1000"
  "-d NO_HZ_FULL"
  "-d NTSYNC"
  "-d USB_MUSB_DUAL_ROLE"
  "-d PREEMPT"
  "-d PREEMPT_DYNAMIC"
  "-d PREEMPT_LAZY"
  "-d PREEMPTION"
  "-d PREEMPT_VOLUNTARY"
  "-d PROFILING"
  "-d SECURITY_SELINUX"
  "-d SECURITY_TOMOYO"
  "-d XEN"

  "-d PM_DEBUG"
  "-d FTRACE_SYSCALLS"
  "-d FUNCTION_TRACER"
  "-d HAMRADIO"
  "-d PINCTRL"
  "-d PINMUX"
  "-d PINCONF"
  "-d SOUND"
  "-d SND"
  "-d SND_SOC"
  "-d SND_SUN4I_CODEC"
  "-d ZRAM_BACKEND_842"
]
++ (import ../config/cmdline.nix) { host = ""; }
#++ (import ../config/vendors.nix) { isPC = false; }
