#!/run/current-system/sw/bin/bash

set -euo pipefail

KERNEL_DIR="./linux"
PATCHES_DIR="./sdm845"

mkdir -p "$PATCHES_DIR"

[ -d "$KERNEL_DIR" ] || git clone https://codeberg.org/sdm845/linux.git "$KERNEL_DIR"
cd "$KERNEL_DIR"

git format-patch 62b712c94718915c9f1c2e8178f507ff58fed61b..HEAD -o "../$PATCHES_DIR"
