keys:
  - &main_machine age1st29vxtalmuzw4je4w3hfcnz8dtadcjf3ksx0742qv0lm5qf7pasw3w3pl
  - &vm_machine age1gzpr4f8nfrlfly7wy9rsyt8nlvh4yeefa5mh37eks4t0j04aq3nq90ld0w
  - &rogally_machine age1r63qsyjw46l8dl96z2jqfxeqsuahm48zf2p3m70khnudxcvm29hs6nyrhx
  - &server_machine age1ktgk5rck3lzmeg2d64wkx2l5v6yq9salpl89gvprem43zr05yyks44n365
  - &opizero_machine age1cz9m3q2ev74ynv9z2lfkamhmuucx852e4yh4yxl6el7ndd25la2qryh9hx
  - &mac_machine age1um6hefxrk8nmjtugnsxfuyltxlk8trxgul5mzlek3m0ncas8gufs2006rt
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *main_machine
          - *vm_machine
          - *rogally_machine
          - *opizero_machine
          - *server_machine
          - *mac_machine
