{ host }:
if host == "v7w7r-rc71l" then
  [
    "-e AMD_PRIVATE_COLOR"
    "-e ASUS_WMI"
    "-e ASUS_NB_WMI"
    "-e BATTERY_ASUS_EC"
    "-e CPU_SUP_AMD"
    "-e CPU_SUP_HYGON"
    "-e DRM_AMD_DC_FP"
    "-e DRM_AMD_DC_SI"
    "-e X86_AMD_PSTATE"
    "-e SND_SOC_SOF_HDA_AUDIO_CODEC"
    "-e SND_HDA_COMPONENT"

    "-m ASUS_ARMOURY"
    "-m AMD_3D_VCACHE"
    "-m AMD_HSMP"
    "-m AMD_PMF"
    "-m AMD_RAPL"
    "-m INTEL_RAPL_CORE"
    "-m INTEL_RAPL"
    "-m KVM_AMD"
    "-m SENSORS_AMD_ENERGY"
    "-m SENSORS_K10TEMP"
    "-m SND_AMD_SOUNDWIRE_ACPI"
    "-m SND_SOC_AMD_SOUNDWIRE"
    "-m SND_SOC_AMD_MACH"
    "-m SND_SOC_AMD_PS"
    "-m SND_SOC_AMD_PS_MACH"
    "-m SND_SOC_SOF_AMD_TOPLEVEL"
    "-m SND_SOC_CS35L41"
    "-m SND_SOC_CS35L41_SOUNDWIRE"
    "-m SND_SOC_CS35L41_I2C"
    "-m SND_SOC_HDAC_HDA"
    "-m SND_HDA_INTEL"
    "-m SND_HDA_CODEC_REALTEK"
    "-m SND_HDA_CODEC_HDMI"
    "-m SND_HDA_EXT_CORE"
    "-m SND_HDA_CORE"
    "-m SOUNDWIRE_AMD"
    "-m V4L2_LOOPBACK"
    "-m VHBA"

    "-d BT_INTEL"
    "-d BT_INTEL_PCIE"
    "-d CPU_SUP_INTEL"
    "-d DRM_I915"
    "-d HAVE_INTEL_TXT"
    "-d INTEL_GTT"
    "-d INTEL_HFI_THERMAL"
    "-d INTEL_IDLE"
    "-d INTEL_IOMMU"
    "-d INTEL_IOMMU_DEFAULT_ON"
    "-d INTEL_IOMMU_PERF_EVENTS"
    "-d INTEL_IOMMU_SCALABLE_MODE_DEFAULT_ON"
    "-d INTEL_IOMMU_SVM"
    "-d INTEL_LDMA"
    "-d INTEL_SCU"
    "-d INTEL_SCU_IPC"
    "-d INTEL_SCU_PCI"
    "-d INTEL_SOC_PMIC"
    "-d INTEL_SOC_PMIC_CHTWC"
    "-d INTEL_TDX_GUEST"
    "-d INTEL_TDX_HOST"
    "-d INTEL_TURBO_MAX_3"
    "-d KVM_INTEL"
    "-d KVM_INTEL_TDX"
    "-d NET_VENDOR_INTEL"
    "-d PERF_EVENTS_INTEL_RAPL"
    "-d PINCTRL_INTEL"
    "-d WLAN_VENDOR_INTEL"
    "-d X86_INTEL_LPSS"
    "-d X86_INTEL_MEMORY_PROTECTION_KEYS"
    "-d X86_INTEL_PSTATE"
    "-d X86_INTEL_TSX_MODE_AUTO"
    "-d X86_MCE_INTEL"
  ]
else
  [
    "-e CPU_SUP_INTEL"
    "-e DRM_I915"
    "-e X86_INTEL_PSTATE"

    "-m BT_INTEL"
    "-m DRM_I915_GVT_KVMGT"
    "-m KVM_INTEL"
    "-m MFD_INTEL_LPSS"
    "-m MFD_INTEL_LPSS_PCI"
    "-m NET_VENDOR_INTEL"

    "-d AMD_3D_VCACHE"
    "-d AMD_HFI"
    "-d AMD_IOMMU"
    "-d AMD_MEM_ENCRYPT"
    "-d AMD_NB"
    "-d AMD_NODE"
    "-d AMD_SECURE_AVIC"
    "-d AMD_WBRF"
    "-d CPU_SUP_AMD"
    "-d CPU_SUP_HYGON"
    "-d KVM_AMD"
    "-d NET_VENDOR_AMD"
    "-d PERF_EVENTS_AMD_BRS"
    "-d PINCTRL_AMD"
    "-d SOUNDWIRE_AMD"
    "-d USB_PCI_AMD"
    "-d X86_AMD_PLATFORM_DEVICE"
    "-d X86_AMD_PSTATE"
    "-d X86_MCE_AMD"
  ]
