{ ... }:
{
  system.activationScripts.postActivation.text = ''

    sudo launchctl disable gui/501/com.apple.XProtect.agent.scan.startup
    sudo launchctl disable gui/501/com.apple.XProtect.agent.scan
    sudo launchctl disable system/com.apple.XProtect.daemon.scan
    sudo launchctl disable system/com.apple.XProtect.daemon.scan.startup

    sudo launchctl disable system/com.apple.PerfPowerServices
    sudo launchctl disable system/com.apple.PerfPowerServicesExtended

    sudo launchctl remove com.apple.CallHistoryPluginHelper
    sudo launchctl remove com.apple.AddressBook.abd
    sudo launchctl remove com.apple.ap.adprivacyd
    sudo launchctl remove com.apple.ReportPanic
    sudo launchctl remove com.apple.ReportCrash
    sudo launchctl remove com.apple.ReportCrash.Self
    sudo launchctl remove com.apple.DiagnosticReportCleanup.plist
    sudo launchctl remove com.apple.ap.adprivacyd
    sudo launchctl remove com.apple.siriknowledged
    sudo launchctl remove com.apple.helpd
    sudo launchctl remove com.apple.mobiledeviceupdater
    sudo launchctl remove com.apple.screensharing.MessagesAgent
    sudo launchctl remove com.apple.TrustEvaluationAgent
    sudo launchctl remove com.apple.iTunesHelper.launcher
    sudo launchctl remove com.apple.softwareupdate_notify_agent
    sudo launchctl remove com.apple.appstoreagent
    sudo launchctl remove com.apple.familycircled
    sudo launchctl remove com.apple.SafariCloudHistoryPushAgent
    sudo launchctl remove com.apple.Safari.SafeBrowsing.Service
    sudo launchctl remove com.apple.SafariNotificationAgent
    sudo launchctl remove com.apple.SafariPlugInUpdateNotifier
    sudo launchctl remove com.apple.SafariHistoryServiceAgent
    sudo launchctl remove com.apple.SafariLaunchAgent
    sudo launchctl remove com.apple.SafariPlugInUpdateNotifier
    sudo launchctl remove com.apple.safaridavclient

    launchctl unload -w /System/Library/LaunchAgents/com.apple.diagnostics_agent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.diagnosticextensionsd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.symptomsd-diag.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.spindump_agent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportPanic.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.sysdiagnose_agent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.generativeexperiencesd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.UsageTrackingAgent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.parentalcontrols.check.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.photoanalysisd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.financed.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.ensemble.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.ndoagent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.icloud.searchpartyuseragent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.assistantd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.transparencyd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.peopled.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.familycircled.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.familycontrols.useragent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.familynotificationd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.progressd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.macos.studentd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.routined.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.homed.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.homeenergyd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.newsd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.gamed.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.siriinferenced.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.corespeechd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.siriknowledged.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.siriactionsd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.amsengagementd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.ContextStoreAgent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.FollowUpUI.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.followupd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.suggestd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.lockdownmoded.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.knowledge-agent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.intelligenceplatformd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.BiomeAgent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.WiFiVelocityAgent.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.triald.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.rapportd-user.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.voicebankingd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.accessibility.axassetsd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.accessibility.heard.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.helpd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.textunderstandingd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.coreservices.useractivityd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.duetexpertd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.betaenrollmentd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.geoanalyticsd.plist
    launchctl unload -w /System/Library/LaunchAgents/com.apple.geodMachServiceBridge.plist

    launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportMemoryException.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.symptomsd-diag.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.symptomsd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.CrashReporterSupportHelper.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.DumpPanic.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.DumpGPURestart.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.icloud.findmydeviced.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.findmymac.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.findmymacmessenger.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.spindump.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.tailspind.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.SubmitDiagInfo.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.awdd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.rapportd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.diagnosticd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.aslmanager.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.triald.system.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.familycontrols.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.sysdiagnose.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.analyticsd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.wifianalyticsd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.wifivelocityd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.systemstats.analysis.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.systemstats.daily.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.audioanalyticsd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.osanalytics.osanalyticshelper.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.watchdogd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.ocspd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.contextstored.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.biomed.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.mobileassetd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.PerfPowerServices.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.powerlogHelperd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.applessdstatistics.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.icloud.searchpartyd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.GameController.gamecontrollerd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.dprivacyd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.coreduetd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.modelcatalogd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.modelmanagerd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.rtcreportingd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.mediaremoted.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.nearbyd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.sandboxd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.aneuserd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.aned.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.periodic-*.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.systemstats.microstackshot_periodic.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.logd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.syslogd.plist
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.newsyslog.plist
  '';
}
